#NUMPY PRACTICE

IMPORT NUMPY


In [5]:
import numpy as np

-creating a 1D Array


In [6]:
a1d = np.array (
    [0,1,2,3,4,5,6,7,8,9]
)

-creating a 2D Array

In [7]:
a2d = np.array (
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)

-creating a 3D Array


In [8]:
a3d = np.array(
    [ [ [1,2],
        [3,4] ],
      [ [5,6],
        [7,8] ]

    ]
)

-output all arrays

In [9]:
print( a1d, a2d, a3d ) #wasnt there a pretty print pprint module that lets me put things better into perspective without converting to strings and cocatenating \n?
# I think its worth the refresh

[0 1 2 3 4 5 6 7 8 9] [[1 2 3]
 [4 5 6]
 [7 8 9]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

-check python list vs. np array


In [13]:
list_a = [1,2,3,4]
list_a

[1, 2, 3, 4]

In [14]:
array_a = np.array(list_a)
array_a

array([1, 2, 3, 4])

In [15]:
array_a*array_a

array([ 1,  4,  9, 16])

-compare execution of numbers from 0 to 1 to the square
#wasnt there sth about using underscores to delineate and make big numbers easier to read? 

In [16]:
list_sq = [i for i in range(1_000_000)]
list_sq;

-check execution time using time.perf_counter()

In [17]:
import time

In [18]:
type(list_sq)
time.perf_counter()

241.782759078

In [19]:
list_sqsq = [i*i for i in list_sq]
time.perf_counter()

242.126527274

In [20]:
array_sq = np.array(list_sq)

In [21]:
time.perf_counter()

242.483987718

In [22]:
array_sqsq = array_sq*array_sq
time.perf_counter()

242.546780735

-query array attributes

In [23]:
a3d.shape

(2, 2, 2)

In [24]:
a3d.size

8

In [25]:
a3d.ndim

3

In [26]:
a3d.shape

(2, 2, 2)

In [27]:
a2d.shape

(3, 3)

In [28]:
a2d.ndim

2

In [29]:
a2d.size

9

In [30]:
a1d.size

10

In [31]:
a1d.shape

(10,)

In [32]:
a1d.ndim

1

In [33]:
a2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
a2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
np.transpose(a2d)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
a3d.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [37]:
np.round(a2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.sin(a2d)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [39]:
np.expand_dims(a3d, 3)

array([[[[1],
         [2]],

        [[3],
         [4]]],


       [[[5],
         [6]],

        [[7],
         [8]]]])

In [40]:
a1d.dtype

dtype('int64')

In [41]:
a3d.dtype

dtype('int64')

In [42]:
x = np.array(['abv'])


In [43]:
x

array(['abv'], dtype='<U3')

In [44]:
x = np.array( [b'abc'] )
x

array([b'abc'], dtype='|S3')

In [45]:
a2d + a2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [46]:
a2d + a3d

ValueError: operands could not be broadcast together with shapes (3,3) (2,2,2) 

In [70]:
a2d*a2d

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [72]:
np.array( [1.23,124.5,124.5], dtype= 'int16' )

array([  1, 124, 124], dtype=int16)

In [73]:
np.zeros( (2,6) )

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [79]:
(np.full( (2,6), 0.0) ).dtype #float64
(np.full( (2,6), 0) ).dtype #int64


dtype('float64')

In [129]:
np.linspace(0,3.14,11)

array([0.   , 0.314, 0.628, 0.942, 1.256, 1.57 , 1.884, 2.198, 2.512,
       2.826, 3.14 ])

In [131]:
np.arange(0,3.14,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.

In [132]:
rng = np.random.default_rng(seed=1) 


In [133]:
rng.random((2,2))

array([[0.51182162, 0.9504637 ],
       [0.14415961, 0.94864945]])

In [134]:
rng.integers(1,7,(2,2))

array([[2, 2],
       [6, 3]])

In [135]:
a1d[0]

0

In [136]:
a2d[0]

array([1, 2, 3])

In [137]:
a3d[0]

array([[1, 2],
       [3, 4]])

In [138]:
a2d[0,2]

3

In [139]:
a2d[0,:]

array([1, 2, 3])

In [140]:
a2d[:,0]

array([1, 4, 7])

In [142]:
a1d[:3]

array([0, 1, 2])

In [143]:
a1d[3:6]

array([3, 4, 5])

In [144]:
a1d[6:]

array([6, 7, 8, 9])

In [145]:
a1d[0:8:2]

array([0, 2, 4, 6])

In [147]:
a2d[:,1:2:-1]

array([], shape=(3, 0), dtype=int64)

In [148]:
a1d[3:0:-1]

array([3, 2, 1])

In [149]:
a1d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [150]:
a2d[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [154]:
list_sq[:];

In [153]:
list_sq[::-1];

In [155]:
a = np.array([0,1,2,3])
b= np.array([2,2,2,2])


In [156]:
-a

array([ 0, -1, -2, -3])

In [157]:
a+b

array([2, 3, 4, 5])

In [158]:
a*b

array([0, 2, 4, 6])

In [159]:
a<b

array([ True,  True, False, False])

In [160]:
a==b

array([False, False,  True, False])

In [162]:
np.array_equal(a,b)

False

In [163]:
a+1

array([1, 2, 3, 4])

In [168]:
a+np.pi + np.e


array([5.85987448, 6.85987448, 7.85987448, 8.85987448])

In [169]:
np.nan

nan

In [170]:
np.sin(a) + np.sqrt(a)

array([0.        , 1.84147098, 2.32351099, 1.87317082])

In [171]:
np.sum(a2d)

45

In [172]:
np.sum(a2d, axis = 0)

array([12, 15, 18])

In [173]:
np.sum(a2d, axis = 1)

array([ 6, 15, 24])

In [174]:
np.min(a2d)

1

In [175]:
np.std(a2d)

2.581988897471611

In [178]:
np.percentile(a2d, 60)

5.8

Exercise: Prices and Amounts ->Total Prices

In [179]:
prices = np.array([3.99,4.99,3.99,12.99])

In [180]:
quantities = np.array ([3,0,0,2])

In [184]:
total = np.sum(prices * quantities )
total

37.95

Exercise: kintetic energy of masses

In [185]:
masses = np.array ([1.2,2.2,1.5,2.0])
velocities = np.array( [12,14,14,7.5])


In [186]:
kin_en = (masses * (velocities**2)) / 2

In [187]:
kin_en

array([ 86.4 , 215.6 , 147.  ,  56.25])

In [188]:
total_kin_en = np.sum(kin_en)
total_kin_en

505.25

In [190]:
print(f'The total kinetic energy is {total_kin_en}, the individual kinetic energies are {total}')

The total kinetic energy is 505.25, the individual kinetic energies are 37.95


Exercise: Centroid of a Triangle

In [191]:
a = np.array ( [5,1])
b = np.array ( [6,8])
c = np.array ( [1,3])

In [192]:
center = (a + b + c)/3

In [193]:
center

array([4., 4.])

-Exercise: sin/cos table and check the unit circle identity (identitty lol)

In [194]:
x = np.arange(0, 2*np.pi,0.01)
x

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.

In [196]:
sin_x = np.sin(x)
sin_x

array([ 0.        ,  0.00999983,  0.01999867,  0.0299955 ,  0.03998933,
        0.04997917,  0.05996401,  0.06994285,  0.07991469,  0.08987855,
        0.09983342,  0.1097783 ,  0.11971221,  0.12963414,  0.13954311,
        0.14943813,  0.15931821,  0.16918235,  0.17902957,  0.18885889,
        0.19866933,  0.2084599 ,  0.21822962,  0.22797752,  0.23770263,
        0.24740396,  0.25708055,  0.26673144,  0.27635565,  0.28595223,
        0.29552021,  0.30505864,  0.31456656,  0.32404303,  0.33348709,
        0.34289781,  0.35227423,  0.36161543,  0.37092047,  0.38018842,
        0.38941834,  0.39860933,  0.40776045,  0.4168708 ,  0.42593947,
        0.43496553,  0.44394811,  0.45288629,  0.46177918,  0.47062589,
        0.47942554,  0.48817725,  0.49688014,  0.50553334,  0.51413599,
        0.52268723,  0.5311862 ,  0.53963205,  0.54802394,  0.55636102,
        0.56464247,  0.57286746,  0.58103516,  0.58914476,  0.59719544,
        0.60518641,  0.61311685,  0.62098599,  0.62879302,  0.63

In [197]:
cos_x = np.cos(x)
cos_x

array([ 1.00000000e+00,  9.99950000e-01,  9.99800007e-01,  9.99550034e-01,
        9.99200107e-01,  9.98750260e-01,  9.98200540e-01,  9.97551000e-01,
        9.96801706e-01,  9.95952733e-01,  9.95004165e-01,  9.93956098e-01,
        9.92808636e-01,  9.91561894e-01,  9.90215996e-01,  9.88771078e-01,
        9.87227283e-01,  9.85584767e-01,  9.83843693e-01,  9.82004235e-01,
        9.80066578e-01,  9.78030915e-01,  9.75897449e-01,  9.73666395e-01,
        9.71337975e-01,  9.68912422e-01,  9.66389978e-01,  9.63770896e-01,
        9.61055438e-01,  9.58243876e-01,  9.55336489e-01,  9.52333570e-01,
        9.49235418e-01,  9.46042344e-01,  9.42754666e-01,  9.39372713e-01,
        9.35896824e-01,  9.32327346e-01,  9.28664636e-01,  9.24909060e-01,
        9.21060994e-01,  9.17120823e-01,  9.13088940e-01,  9.08965750e-01,
        9.04751663e-01,  9.00447102e-01,  8.96052498e-01,  8.91568288e-01,
        8.86994923e-01,  8.82332859e-01,  8.77582562e-01,  8.72744508e-01,
        8.67819180e-01,  

In [201]:
tabular = np.array([x,sin_x,cos_x])
tabular

array([[ 0.00000000e+00,  1.00000000e-02,  2.00000000e-02, ...,
         6.26000000e+00,  6.27000000e+00,  6.28000000e+00],
       [ 0.00000000e+00,  9.99983333e-03,  1.99986667e-02, ...,
        -2.31832300e-02, -1.31849251e-02, -3.18530179e-03],
       [ 1.00000000e+00,  9.99950000e-01,  9.99800007e-01, ...,
         9.99731233e-01,  9.99913075e-01,  9.99994927e-01]])

-check the sin^2 + cos^2 = 1 identity


In [204]:
identity = (tabular[1, :] )**2 + (tabular[2,:] )**2
identity

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

Exercise: Simulate 1 million dice rolls with 10 dice each

In [47]:
#rng wasnt defined for some reason, so do it here as follows
rng = np.random.default_rng(seed=1)
dice_rolls = rng.integers(1,7,(1_000_000,10))

In [51]:
dice_rolls


array([[3, 4, 5, ..., 6, 2, 2],
       [6, 3, 2, ..., 4, 1, 1],
       [6, 5, 6, ..., 5, 1, 2],
       ...,
       [4, 5, 1, ..., 1, 1, 3],
       [2, 3, 3, ..., 4, 2, 5],
       [4, 6, 5, ..., 2, 6, 3]])

In [52]:
erste_roll = dice_rolls[:,0]
erste_roll

array([3, 6, 6, ..., 4, 2, 4])

In [48]:
# isnt the row the first rolls though and not the column? and shouldnt the column output a million outputs and not just 10 ???
#ich glaube schon

In [53]:
erste_roll = dice_rolls[0,:]
erste_roll

array([3, 4, 5, 6, 1, 1, 5, 6, 2, 2])

In [54]:
a = rng.integers(-10,10,(1,6))
a

array([[-5,  5,  9, -6, -3, -5]])

In [55]:
a_filtered = a[a>0]
a_filtered

array([5, 9])

In [59]:
a_with_nan = np.copy(a)
a_with_nan = np.array(a, dtype='float')


a_with_nan[a_with_nan<0] = np.nan
a_with_nan

array([[nan,  5.,  9., nan, nan, nan]])

In [60]:
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [67]:
np.reshape(a3d, (8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [68]:
np.reshape(a3d, (2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
np.ravel(a3d)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
np.reshape(a3d, (-1, ))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
np.reshape(a3d, (2,-1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
np.expand_dims(a2d, 1)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [81]:
np.expand_dims(a2d,0)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [82]:
np.expand_dims(a2d, 2)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [85]:
a2d[:,:,np.newaxis]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [86]:
np.transpose(a2d)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [87]:
a2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [88]:
a2d.T.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
array = rng.integers(1,10, (3))
array

array([5, 5, 3])

In [59]:
array_view = array[:]


array_view

array([5, 5, 3])

In [60]:
array_view[2] = 10
array_view

array([ 5,  5, 10])

In [61]:
array

array([ 5,  5, 10])

In [62]:
arra_view = np.copy(array)

In [63]:
arra_view[1] = 2
arra_view

array([ 5,  2, 10])

In [64]:
array

array([ 5,  5, 10])

In [65]:
array_view

array([ 5,  5, 10])

In [66]:
np.concatenate([a1d,a1d])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.concatenate([a2d,a2d])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
np.concatenate([a2d,a2d], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [69]:
np.stack([a1d, a1d])

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [71]:
np.stack([a2d,a2d])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [73]:
points = np.array([[0,0], [1,0], [0,1], [1,1]])
m = np.array([[np.sqrt(0.5), np.sqrt(0.5)],
[-np.sqrt(0.5), np.sqrt(0.5)]])

In [74]:
turn_45 = points@m
turn_45

array([[ 0.        ,  0.        ],
       [ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678],
       [ 0.        ,  1.41421356]])

In [75]:
turn_90 =points@m@m
turn_90

array([[ 0.00000000e+00,  0.00000000e+00],
       [ 4.26642159e-17,  1.00000000e+00],
       [-1.00000000e+00, -4.26642159e-17],
       [-1.00000000e+00,  1.00000000e+00]])

In [77]:
turn_360 = points @m @m @m @m @m @m @m @m
turn_360

array([[ 0.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00, -1.27814294e-16],
       [ 2.91949520e-17,  1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00]])

In [78]:
np.transpose(m)

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [79]:
np.linalg.inv(m)

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [80]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [86]:
prices = np.array ( [3.99,12.99,5.90,15])
quantities = np.array([[0,80,80,100],
[100,0,0,0],
[50,0,0,50]])

In [101]:
total = quantities@prices
np.shape(total)

(3,)

In [100]:
np.shape(prices@quantities.T)


(3,)

In [96]:
np.shape(prices)

(4,)

In [98]:
np.shape(quantities)

(3, 4)

In [99]:
np.sum(total)

4359.7